### ISSUE TITLE
Looking Forward

### ISSUE THREAD

**Issue by nousr** [dymokomi/dygen#1]
Hey! Glad to see this code make its way into the open <3 

I wanted to gauge your interest in public contributions to this repo?

Would you prefer that people fork this and develop code separately from your own advancements? Or, would you like this to be THE place to come and get the latest version of dygen tools?

Depending on the answer to those questions some others may follow, but just figured i'd start the discussion!

**Comment by dymokomi** [comment]
I'm interested in public contributions, but I don't want to force it on anyone. If people prefer to fork and cook up their own algorithms on top - it will still make me happy. I'll appreciate and review requests and try my best to merge, but my biggest fear is the burden of maintaining clean, well documented code, as I'm a very messy coder myself. If someone will want to help with it - great! If not - I'll try to do my best. It would be nice to see this library grow, of course.

**Comment by dymokomi** [comment]
closing
